# Generated by Django 5.1.4 on 2024-12-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected'), ('Offer Accepted', 'Offer Accepted'), ('Offer Declined', 'Offer Declined')], default='Pending', max_length=20)),
                ('job_link', models.URLField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
    ]
