# Generated by Django 5.1.4 on 2024-12-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
